name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  try-frontend-build:
    runs-on: ubuntu-20.04
    env: 
      DISABLE_ESLINT_PLUGIN: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.0"
      - name: try build frontend
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" > .env
          npm install
          npm run build
